# *****************************************************************
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2018, 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# *****************************************************************
#
# All jobs defined in this file will fire when a PR is pushed.
# For now, this file should be included in the PR and only include
# the package(s) being addressed.

env:
  global:
    # The BINSTAR Token for uploading to anaconda.org/powerai
    - secure:  
    
    
  jobs:
    include:
      tensorflow-metadata recipe
      - stage: tensorflow-metadata
        language: generic

        os: linux-ppc64le

        env: CONDA_PY="" CONFIG=linux_noarch UPLOAD_PACKAGES=True

        script:
            -  cd conda-recipes/tensorflow-metadata-feedstock
            -  ./ci_support/run_docker_build.sh tensorflow-metadata-0.13-py
